name: Workflows Deploy Release App

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2

  ktlint:
    name: Run KtLint Check Code
    needs: [ setup ]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Run KtLint
        run: ./gradlew ktlint

  build-and-deploy-app:
    name: Build & Deploy Release App
    needs: [ setup, ktlint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - id: sign_app
        name: Sign App APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK Build on Firebase Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          file: app/build/outputs/apk/release/app-release.apk
          releaseNotes: ${{ github.event.pull_request.title }}