name: Run workflows pull request master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]

jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2

  ktlint:
    name: Run KtLint Check Code
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Run KtLint
        run: ./gradlew ktlint

  unittest:
    name: Run Unit Test
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Run unit test
        run: ./gradlew testDebugUnitTest
